### PR TITLE
Use DB_PORT environment variable

### PR DESCRIPTION
**Pull request by Rakdos8**
Related documentation: https://dev.mysql.com/doc/refman/5.7/en/mysqladmin.html

### CODE REVIEW

**Comment by warlof** [comment]
@leonjza sounds good for a merge :)

**Comment by Rakdos8** [comment]
I would rather prefer this one to every `startup.sh`: https://github.com/eveseat/docker-eveseat-app/pull/6/files#diff-d0486b0d7b181591f52bad014cd3a06fR10

Should I open a new pull request to each repository ?

**Comment by warlof** [comment]
Sure you can. Just update the current one for this repo

**Comment by Rakdos8** [comment]
Commit updated.
Is there any chance to get this deployed anytime soon ? I'm looking forward to use it on my kubernetes cluster :) .

**Pull request merged**
